In [2]:
import sympy as sym
import numpy as np
from IPython.display import display,Math

In [6]:
A = np.array([ [1,2],[3,4] ])

In [10]:
print(A)
display(Math(sym.latex(sym.sympify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [14]:
mat = np.zeros([4,6])

mat[2,4] = 7
mat[0,1] = 2

mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
numrange = range(0,2)

for rowi in numrange:
    for coli in numrange:
        mat[rowi, coli] = (-1)**(rowi+coli)
        
mat

array([[ 1., -1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  7.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [18]:
x,y = sym.symbols('x y')

Fxy = (4+x)*(2-y)

xyset = range(0,3)

outmat = np.zeros([len(xyset),len(xyset)])

for i in xyset:
    for j in xyset:
        outmat[i,j] = Fxy.subs({x:i,y:j})
        
outmat

display(Math(sym.latex(sym.simplify(outmat))))

<IPython.core.display.Math object>

In [12]:
nums = range(1,11)

matmult = np.zeros((len(nums),len(nums)))

for rowi in nums:
    for coli in nums:
        print(rowi,coli)
        matmult[rowi,coli] = rowi*coli

1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
1 10


IndexError: index 10 is out of bounds for axis 1 with size 10